plugins {
    id 'java'
    id 'me.champeau.jmh' version '0.7.2'
}

jar {
    archiveBaseName = 'alg_practice'
}
group = 'org.theory'
version = '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

test {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed'
    }
}

jmh {
    iterations = 3
    timeOnIteration = '1s'
    warmupBatchSize = 1
    warmupIterations = 1
    warmup = '1s'
    humanOutputFile = project.file('result.txt')
}

dependencies {
    jmh 'commons-lang:commons-lang:2.6'

    implementation     'org.junit.jupiter:junit-jupiter-api:5.11.4'    // also used by embedded tests in src/main/java
    testRuntimeOnly    'org.junit.jupiter:junit-jupiter-engine:5.11.4'
    implementation     'org.assertj:assertj-core:3.27.2'               // also used by embedded tests in src/main/java
}
